version: '3.7'
services:
  db:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    ports:
      - 3306:3306
volumes:
  mysql-data:
