name: Check Actions

on:
  pull_request:

jobs:
  test_hider:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `aaa`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - uses: kanga333/comment-hider@update-to-node16
      name: Hide bot comments
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  test_variable_mapper:
    runs-on: ubuntu-latest
    steps:
    - uses: kanga333/variable-mapper@update-to-node16
      with:
        key: "${{github.base_ref}}"
        map: |
          {
            "master": {
              "environment": "production"
            },
            "staging": {
              "environment": "staging"
            },
            ".*": {
              "environment": "development"
            }
          }
    - name: Echo environment
      run: echo ${{ env.environment }}
  test_json_array_builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kanga333/json-array-builder@update-to-node16
      id: array
      with:
        cmd: ls 
        separator: newline
    - name: Echo environment
      run: echo ${{ steps.array.outputs.build }}
