on:
  pull_request:
    types: "labeled"
name: add commit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: add commit
      run: |
        echo "test" >> test.txt
        git add . 
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git commit --author=. -m 'test'
        git branch
        git remote
        git push origin ${ github.head_ref }

