on: [pull_request]
name: diff_check
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: calculate depth
      id: c
      run: |
        depth=$(( ${{github.event.pull_request.commits}} + 1 ))
        echo "::set-output name=DEPTH::$depth"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # - uses: actions/checkout@v3
    #   with:
    #     ref: ${{github.base_ref}}
    - name: echo result
      run: |
        git branch
        git checkout '${{github.head_ref}}'
        echo '${{github.base_ref}}'
        echo '${{github.head_ref}}'
        git diff --diff-filter=ACMR --name-only 'origin/${{github.base_ref}}' 'origin/${{github.head_ref}}'
        echo '${{github.ref}}'
