on: [pull_request]
name: diff_check
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: actions/checkout@v3
    #   with:
    #     ref: ${{github.base_ref}}
    - name: echo result
      run: |
        git branch
        echo '${{github.base_ref}}'
        echo '${{github.head_ref}}'
        git diff --diff-filter=ACMR --name-only '${{github.base_ref}}' '${{github.head_ref}}'
        echo '${{github.ref}}'
