name: Reproduction test

on:
  pull_request:

jobs:
  build_ci_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{github.base_ref}}"
          map: |
            {
              "master": {
                "VITE_ENVIRONMENT": "production"
              },
              "develop": {
                "VITE_ENVIRONMENT": "staging"
              },
              ".*": {
                "VITE_ENVIRONMENT": "development"
              }
            }
