on: [push]
name: success case
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_STRING: |
        one
        two
        three
    steps:
    - uses: kanga333/variable-mapper@master
      with:
        key: "key"
        map: |
          {
            ".*": {
              "result": ${{ toJSON(env.TEST_STRING) }}
            }
          }
    - name: Echo result
      run: echo ${{ env.result }}
