on: [push]
name: https://github.com/kanga333/variable-mapper/issues/30
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_STRING: |
        aaa
        bbb
    steps:
    - name: Echo Plain
      run: echo "${{ env.TEST_STRING }}"
    - name: Echo is_match
      run: echo "${{ toJSON(env.TEST_STRING) }}"
